{{- if .Values.pgvector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-pgvector
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pgvector
      protocol: TCP
      name: pgvector
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
{{- end }}
