export const CONVERSATION_SIDEBAR_SELECTORS = {
  collapsedSidebarWrapper: "chatCollapsedConversationSidebarWrapper",
  expandedSidebarWrapper: "chatExpandedConversationSidebarWrapper",
  expandedSidebarChatList: "expandedSidebarChatList",
  collapsedSidebarChatList: "collapsedSidebarChatList",
  collapsedChatListItem: "collapsedChatListItem",
  expandedChatListItem: "expandedChatListItem",
  collapsedAddChatButton: "collapsedAddChatButton",
  expandedAddChatButton: "expandedAddChatButton",
  collapseSidebarButton: "collapseSidebarButton",
  expandSidebarButton: "expandSidebarButton",
  chatEllipsisButton: "chatEllipsisButton",
  editChatButton: "editChatButton",
  deleteChatButton: "deleteChatButton",
  updateChatContentWrapper: "updateChatContentWrapper",
  updateChatTextField: "updateChatTextField",
  saveChatButton: "saveChatButton",
}
