
name: lint-frontend

on:
  pull_request:
    branches:
      - '**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint-frontend:
    name: lint-frontend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    strategy:
      matrix:
        node-version: [22.x, "node"]
    steps:
      - name: Checkout to ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint files
        run: pnpm run lint

      - name: Prettier
        run: pnpm run prettier